/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorgui;

import java.util.ArrayList;

/**
 *
 * @author Kate
 */
public class CalculatorGUI extends javax.swing.JFrame {

    String numberOne = "";
    String numberTwo = "";
    double result = 0;
    String operator = "";
    ArrayList<String> line = new ArrayList<String>();
    String expresion = "";
    
    /**
     * Creates new form CalculatorGUI
     */
    public CalculatorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton17 = new javax.swing.JButton();
        jbutton8 = new javax.swing.JButton();
        jbuttonClearAll = new javax.swing.JButton();
        jbutton7 = new javax.swing.JButton();
        jbutton5 = new javax.swing.JButton();
        jbutton4 = new javax.swing.JButton();
        jbutton1 = new javax.swing.JButton();
        jbutton0 = new javax.swing.JButton();
        jbuttonDot = new javax.swing.JButton();
        jbutton2 = new javax.swing.JButton();
        jbuttonMultip = new javax.swing.JButton();
        jbutton3 = new javax.swing.JButton();
        jbutton6 = new javax.swing.JButton();
        jbutton9 = new javax.swing.JButton();
        jbuttonClear = new javax.swing.JButton();
        inputText = new javax.swing.JTextField();
        jbuttonDevide = new javax.swing.JButton();
        jbuttonPlus = new javax.swing.JButton();
        jbuttonEgal = new javax.swing.JButton();
        jbuttonMinus = new javax.swing.JButton();

        jButton17.setText("jButton17");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        jbutton8.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbutton8.setText("8");
        jbutton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton8ActionPerformed(evt);
            }
        });

        jbuttonClearAll.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbuttonClearAll.setText("C");
        jbuttonClearAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonClearAllActionPerformed(evt);
            }
        });

        jbutton7.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbutton7.setText("7");
        jbutton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton7ActionPerformed(evt);
            }
        });

        jbutton5.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbutton5.setText("5");
        jbutton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton5ActionPerformed(evt);
            }
        });

        jbutton4.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbutton4.setText("4");
        jbutton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton4ActionPerformed(evt);
            }
        });

        jbutton1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbutton1.setText("1");
        jbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton1ActionPerformed(evt);
            }
        });

        jbutton0.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbutton0.setText("0");
        jbutton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton0ActionPerformed(evt);
            }
        });

        jbuttonDot.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbuttonDot.setText(".");
        jbuttonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonDotActionPerformed(evt);
            }
        });

        jbutton2.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbutton2.setText("2");
        jbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton2ActionPerformed(evt);
            }
        });

        jbuttonMultip.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbuttonMultip.setText("*");
        jbuttonMultip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonMultipActionPerformed(evt);
            }
        });

        jbutton3.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbutton3.setText("3");
        jbutton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton3ActionPerformed(evt);
            }
        });

        jbutton6.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbutton6.setText("6");
        jbutton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton6ActionPerformed(evt);
            }
        });

        jbutton9.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbutton9.setText("9");
        jbutton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutton9ActionPerformed(evt);
            }
        });

        jbuttonClear.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbuttonClear.setText("CE");
        jbuttonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonClearActionPerformed(evt);
            }
        });

        inputText.setBackground(new java.awt.Color(240, 240, 240));
        inputText.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        inputText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        inputText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTextActionPerformed(evt);
            }
        });

        jbuttonDevide.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbuttonDevide.setText("/");
        jbuttonDevide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonDevideActionPerformed(evt);
            }
        });

        jbuttonPlus.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbuttonPlus.setText("+");
        jbuttonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonPlusActionPerformed(evt);
            }
        });

        jbuttonEgal.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbuttonEgal.setText("=");
        jbuttonEgal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonEgalActionPerformed(evt);
            }
        });

        jbuttonMinus.setFont(new java.awt.Font("Tempus Sans ITC", 0, 11)); // NOI18N
        jbuttonMinus.setText("-");
        jbuttonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonMinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jbutton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbutton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbutton0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbutton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbutton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbutton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbuttonDot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbutton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jbutton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbutton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbutton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbuttonMultip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbuttonClear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbuttonClearAll)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jbuttonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbuttonDevide, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbuttonMinus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jbuttonEgal))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(inputText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuttonClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbuttonDevide, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jbuttonClearAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuttonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbutton8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbutton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbutton6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbutton4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbutton3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addComponent(jbutton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbutton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jbuttonPlus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbuttonMultip, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jbuttonDot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbutton0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbuttonEgal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbutton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton8ActionPerformed
        line.add("8");
        expresion += "8";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbutton8ActionPerformed

    private void jbuttonClearAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonClearAllActionPerformed
        numberOne = "";
        numberTwo = "";
        operator = "";
        result = 0;
        this.inputText.setText("");
        for (int i = 0; i < line.size(); i++) {
            line.remove(i);
        }
        expresion = "";

    }//GEN-LAST:event_jbuttonClearAllActionPerformed

    private void jbutton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton7ActionPerformed
        line.add("7");
        expresion += "7";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbutton7ActionPerformed

    private void jbutton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton5ActionPerformed
        line.add("5");
        expresion += "5";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbutton5ActionPerformed

    private void jbuttonMultipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonMultipActionPerformed
        operator = "*";
        line.add("*");
        expresion += "*";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbuttonMultipActionPerformed

    private void jbutton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton9ActionPerformed
        line.add("9");
        expresion += "9";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbutton9ActionPerformed

    private void jbuttonEgalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonEgalActionPerformed
        if (operator.equals("*")) {
            for (int i = 0; i < line.indexOf("*"); i++) {
                numberOne += line.get(i);
            }
            for (int i = line.indexOf("*") + 1; i < line.size(); i++) {
                numberTwo += line.get(i);
            }
            result = Double.parseDouble(numberOne) * Double.parseDouble(numberTwo);
            expresion = String.valueOf(result);
            this.inputText.setText(expresion);
        }
        if (operator.equals("/")) {
            for (int i = 0; i < line.indexOf("/"); i++) {
                numberOne += line.get(i);
            }
            for (int i = line.indexOf("/") + 1; i < line.size(); i++) {
                numberTwo += line.get(i);
            }
            result = Double.parseDouble(numberOne) / Double.parseDouble(numberTwo);
            expresion = String.valueOf(result);
            this.inputText.setText(expresion);
        }
        if (operator.equals("-")) {
            for (int i = 0; i < line.indexOf("-"); i++) {
                numberOne += line.get(i);
            }
            for (int i = line.indexOf("-") + 1; i < line.size(); i++) {
                numberTwo += line.get(i);
            }
            result = Double.parseDouble(numberOne) - Double.parseDouble(numberTwo);
            expresion = String.valueOf(result);
            this.inputText.setText(expresion);
        }
        if (operator.equals("+")) {
            for (int i = 0; i < line.indexOf("+"); i++) {
                numberOne += line.get(i);
            }
            for (int i = line.indexOf("+") + 1; i < line.size(); i++) {
                numberTwo += line.get(i);
            }
            result = Double.parseDouble(numberOne) + Double.parseDouble(numberTwo);
            expresion = String.valueOf(result);
            this.inputText.setText(expresion);
        }
    }//GEN-LAST:event_jbuttonEgalActionPerformed

    private void jbuttonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonPlusActionPerformed
        operator = "+";
        line.add("+");
        expresion += "+";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbuttonPlusActionPerformed

    private void jbuttonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonMinusActionPerformed
        operator = "-";
        line.add("-");
        expresion += "-";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbuttonMinusActionPerformed

    private void jbutton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton0ActionPerformed
        line.add("0");
        expresion += "0";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbutton0ActionPerformed

    private void jbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton1ActionPerformed
        line.add("1");
        expresion += "1";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbutton1ActionPerformed

    private void jbutton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton4ActionPerformed
        line.add("4");
        expresion += "4";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbutton4ActionPerformed

    private void jbuttonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonClearActionPerformed
        expresion = "";
        for (int i = 0; i<line.size()-1; i++){
            expresion += line.get(i);}
            this.inputText.setText(expresion);
           
    }//GEN-LAST:event_jbuttonClearActionPerformed

    private void jbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton2ActionPerformed
        line.add("2");
        expresion += "2";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbutton2ActionPerformed

    private void jbuttonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonDotActionPerformed
        line.add(".");
        expresion += ".";
        this.inputText.setText(expresion);

    }//GEN-LAST:event_jbuttonDotActionPerformed

    private void jbutton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton6ActionPerformed
        line.add("6");
        expresion += "6";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbutton6ActionPerformed

    private void jbutton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutton3ActionPerformed
        line.add("3");
        expresion += "3";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbutton3ActionPerformed

    private void jbuttonDevideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonDevideActionPerformed
        operator = "/";
        line.add("/");
        expresion += "/";
        this.inputText.setText(expresion);
    }//GEN-LAST:event_jbuttonDevideActionPerformed

    private void inputTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTextActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_inputTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputText;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jbutton0;
    private javax.swing.JButton jbutton1;
    private javax.swing.JButton jbutton2;
    private javax.swing.JButton jbutton3;
    private javax.swing.JButton jbutton4;
    private javax.swing.JButton jbutton5;
    private javax.swing.JButton jbutton6;
    private javax.swing.JButton jbutton7;
    private javax.swing.JButton jbutton8;
    private javax.swing.JButton jbutton9;
    private javax.swing.JButton jbuttonClear;
    private javax.swing.JButton jbuttonClearAll;
    private javax.swing.JButton jbuttonDevide;
    private javax.swing.JButton jbuttonDot;
    private javax.swing.JButton jbuttonEgal;
    private javax.swing.JButton jbuttonMinus;
    private javax.swing.JButton jbuttonMultip;
    private javax.swing.JButton jbuttonPlus;
    // End of variables declaration//GEN-END:variables
}
